name = "jlog-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
WEB_ORIGIN = "https://jlog-web.pages.dev"
COOKIE_DOMAIN = "production"

[[d1_databases]]
binding = "DB"
database_name = "jlog"
database_id = "8247e5bd-5d9d-4616-95cb-aa4cffee19ee"
